apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ping-iam

resources:
  - namespace.yaml
  - react-app.yaml
  - backend-api.yaml
  - service-export.yaml

# Note: Gateway resources are applied separately to MCI config cluster only
# Note: ping-devops Helm chart is deployed separately via helm upgrade
