apiVersion: v1
kind: Secret
metadata:
  name: ping-devops-credentials
  namespace: ping-iam
type: Opaque
stringData:
  # Ping Identity DevOps credentials - Required for pulling images
  # Get credentials at: https://devops.pingidentity.com/get-started/devopsRegistration/
  PING_IDENTITY_DEVOPS_USER: "${PING_IDENTITY_DEVOPS_USER}"
  PING_IDENTITY_DEVOPS_KEY: "${PING_IDENTITY_DEVOPS_KEY}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ping-admin-passwords
  namespace: ping-iam
type: Opaque
stringData:
  # PingDirectory
  ROOT_USER_PASSWORD: "2FederateM0re"
  # PingFederate
  PF_ADMIN_USER_PASSWORD: "PingFederate123!"
  # PingAccess
  PA_ADMIN_PASSWORD: "PingAccess123!"
